=== mpobjects/sofalife/src/main/resources/sofalife.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://system.mp-objects.com/schemas/sofalife" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:sl="http://system.mp-objects.com/schemas/sofalife">

    <element name="format" type="sl:Format"></element>

    <complexType name="Record">
    	<annotation>
    		<documentation>A single record.</documentation>
    	</annotation>
    	<sequence>
    		<element name="description" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="field" type="sl:Field" maxOccurs="unbounded" minOccurs="0"></element>
    		<element name="record" type="sl:Record" maxOccurs="unbounded" minOccurs="0">
    			<annotation>
    				<documentation>Nested records.</documentation>
    			</annotation>
    		</element>
    	</sequence>
    	<attribute name="qualifier" type="string" use="required">
    		<annotation>
    			<documentation>
    				The identifier for the record. The start of the read content must match this identifier.
    			</documentation>
    		</annotation>
    	</attribute>
    	<attribute name="multiplicity" type="string" default="1..*">
    		<annotation>
    			<documentation>Is this element optional.</documentation>
    		</annotation>
    	</attribute>
    	<attribute name="name" type="NCName">
    		<annotation>
    			<documentation>Used to generate the XML element with. If not used the identifier value will be normalized to be a value NCName.</documentation>
    		</annotation></attribute>
    </complexType>

    <complexType name="Field">
    	<sequence>
    		<element name="description" type="string" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    	<attribute name="name" type="NCName" use="required">
    		<annotation>
    			<documentation>The name of this field. Will be used to generate the XML element with.</documentation>
    		</annotation></attribute>
    	<attribute name="length" type="int" use="required">
    		<annotation>
    			<documentation>The length of the field.</documentation>
    		</annotation></attribute>
    	<attribute name="optional" type="boolean" default="false">
    		<annotation>
    			<documentation>Defines if this field is optional. If this field is optional and not present, then all additional fields will be ignored as well. Thus all subsequent fields will automatically be made optional.</documentation>
    		</annotation></attribute>
    </complexType>

    <complexType name="Format">
    	<sequence>
    		<element name="description" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="record" type="sl:Record" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    	<attribute name="version" type="string"></attribute>
    	<attribute name="id" type="Name">
    		<annotation>
    			<documentation>The identifier for this format.</documentation>
    		</annotation>
    	</attribute>
    	<attribute name="encoding" type="NCName">
    		<annotation>
    			<documentation>Input character encoding.</documentation>
    		</annotation>
    	</attribute>
    	<attribute name="name" type="NCName" use="optional">
    		<annotation>
    			<documentation>The name of the root element.</documentation>
    		</annotation></attribute>
    </complexType>
</schema>

=== mpobjects/sofalife/src/test/resources/example-spec.xml
<?xml version="1.0" encoding="UTF-8"?>
<format encoding="utf-8" id="com:mpobjects:sofalife:example" name="example" version="1.0" xmlns="http://system.mp-objects.com/schemas/sofalife"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://system.mp-objects.com/schemas/sofalife ../../main/resources/sofalife.xsd">

	<description>Example specification to show off sofalife</description>

	<record qualifier="AAA" name="header" multiplicity="1">
		<field length="8" name="message-id" />
		<field length="8" name="date" />
		<field length="6" name="time" />
		<field length="5" name="sender" />
	</record>

	<record qualifier="REC">
		<field length="8" name="record-id" />

		<record qualifier="LOC" name="location" multiplicity="2">
			<description>Sender/Receiver information</description>
			<field length="1" name="type" />
			<field length="20" name="name" />
			<field length="20" name="address" />
			<field length="20" name="city" />
			<field length="20" name="country" />
		</record>

		<record qualifier="ITM" name="item">
			<field length="4" name="item-id" />
			<field length="20" name="name" />
			<field length="5" name="count" />
			<field length="60" name="description" optional="true" />

			<record qualifier="MEA" name="measurement" multiplicity="*">
				<field length="10" name="type" />
				<field length="10" name="value" />
				<field length="3" name="unit" />
			</record>
		</record>
	</record>

	<record qualifier="ZZZ" name="footer" multiplicity="1">
		<field length="4" name="count" />
		<field length="1" name="endbit" />
	</record>

</format>
